# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{brfaker}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rafael Felix"]
  s.date = %q{2011-01-20}
  s.description = %q{Generate Brazilian faker documents}
  s.email = %q{felix.rafael@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "lib/brfaker.rb",
    "lib/brfaker/cpf_cnpj/cnpj.rb",
    "lib/brfaker/cpf_cnpj/cpf.rb",
    "lib/brfaker/cpf_cnpj/cpf_cnpj.rb",
    "lib/brfaker/version.rb",
    "lib/extensions/array.rb",
    "lib/extensions/string.rb",
    "test/helper.rb",
    "test/test_cnpj.rb",
    "test/test_cpf.rb"
  ]
  s.homepage = %q{http://github.com/fellix/brfaker}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Generate Brazilian faker documents}
  s.test_files = [
    "test/helper.rb",
    "test/test_cnpj.rb",
    "test/test_cpf.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<brcpfcnpj>, [">= 3.0.2"])
      s.add_development_dependency(%q<activerecord>, [">= 3.0.0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<brcpfcnpj>, [">= 3.0.2"])
      s.add_dependency(%q<activerecord>, [">= 3.0.0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<brcpfcnpj>, [">= 3.0.2"])
    s.add_dependency(%q<activerecord>, [">= 3.0.0"])
  end
end

